### ISSUE TITLE
Support Symfony 3

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#105]
In the course of iterating on #104, I discovered that tests fail if we require `symfony/validator:^3.4`. That's a problem for older versions of Drupal 8 which might want to leverage TUF. If Symfony 3 is still getting security fixes, we should probably support it.

**Comment by xjm** [comment]
Drupal 8.9 uses Syomfony 3.4 also, so we have more of an interest in this one than Guzzle 5.

**Comment by phenaproxima** [comment]
We'll need to make sure we're testing against all major versions of Symfony; see #107 for discussion on that.

**Comment by phenaproxima** [comment]
According to https://endoflife.date/symfony, Symfony 3 is completely EOL. Should we close this, @xjm?

**Comment by xjm** [comment]
From Drupal's perspective, yes, this can be closed. We should double-check that Joomla and TYPO3 also aren't using Symfony 3. (I don't think they use Symfony at all, but we should confirm it in any case.)

**Comment by phenaproxima** [comment]
I don't think we need to keep this open. We had to bump our minimum PHP version to 8.1, and therefore Symfony 3 support is a moot point.
