### ISSUE TITLE
Support Guzzle 5

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#106]
Similar to #105, Guzzle 5 is still supported and we should probably support it too, if we can. #104 revealed that tests fail under Guzzle 5, so this issue is to discuss supporting it.

**Comment by xjm** [comment]
While it has security coverage it has not had a release in 18 months, so it's EOLish. For this issue we can decide whether or not it's worth the time to try to support Guzzle 5 depending on whether any of our peer projects still use it.
