### ISSUE TITLE
Test against all supported major versions of our dependencies

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#107]
In #104, we explicitly declared support for multiple major versions of Symfony and Guzzle. We also need to be sure we're testing against each of those major versions; right now, we're just testing against the latest supported version. Let's adjust our CI configuration to have a matrix of major dependency versions that we can test against.

**Comment by xjm** [comment]
https://github.com/php-tuf/php-tuf/blob/main/.github/workflows/php.yml is the file to change to do this.
