### ISSUE TITLE
Metadata is 1 word. Fix casing in variable names and other places.

### ISSUE THREAD

**Issue by tedbow** [php-tuf/php-tuf#148]
Since metadata is 1 word. We should not have var names like `$targetMetaData` but use `$targetMetadata` and for functions instead of `fetchMetaData()` we should use `fetchMetadata()`

We need a PR to change all these instances.

**Comment by SpyroL7** [comment]
hi, could I assigned to this?

**Comment by phenaproxima** [comment]
Sure, thank you!

**Comment by tedbow** [comment]
@SpyroL7 thanks jumping. Let me know if you need anything. 

PS if you want to discuss this project there 2 good places(besides this repo) Drupal slack https://www.drupal.org/join-slack in `#autoupdates` channel or [#tuf](https://cloud-native.slack.com/archives/C8NMD3QJ3) in cloud native slack

**Comment by phenaproxima** [comment]
This is addressed in #157.

**Comment by tedbow** [comment]
@SpyroL7 thanks for #157 !

There are still some cases left though. Now all instances of `metaData` are gone but there are still instances of `MetaData`(with capitpal "M" and "D". For example `$newSnapshotData->verifyNewMetaData($newTargetsData);` in `Updater.php`.  This should be changed to `$newSnapshotData->verifyNewMetadata($newTargetsData);`

So we need to replace all instances of `MetaData` with `Metadata`, preserving the capital "M" in this case

Thanks

**Comment by tedbow** [comment]
@SpyroL7 I am unassigning from just you just because I am not sure if you have time to still work on this. If you want to create a new PR for this that would be great and we can re-assign to you. Thanks

**Comment by SpyroL7** [comment]
@tedbow Hi, sorry about that - I thought I had changed all of those as well, but it seems in the first few files I didn't change these. I have made these changes now and can push them shortly.

**Comment by tedbow** [comment]
@SpyroL7 no problem. thanks!

**Comment by tedbow** [comment]
#158  got the rest. @SpyroL7 thanks for finishing it up!
