### ISSUE TITLE
Update DEPENDENCIES.md with current dependencies

### ISSUE THREAD

**Issue by tedbow** [php-tuf/php-tuf#150]
DEPENDENCIES.md is meant to document our dependencies but it is not up to date.

For instance we longer have direct dev dependency on `PHP_CodeSniffer`

We need to make sure this file is up-to-date

**Comment by ajfwebdev** [comment]
I'm looking into this issue.

**Comment by ajfwebdev** [comment]
We don't have a direct dependency on squizlabs/php_codesniffer. The php-tuf/phpcodesniffer-standard depends on it. 

@tedbow, should the DEPENDENCIES.md include php-tuf dependencies, like  php-tuf/phpcodesniffer-standard?

**Comment by tedbow** [comment]
@ajfwebdev yeah I think we can skip anything in `php-tuf/` org

**Comment by ajfwebdev** [comment]
Submitted a PR: https://github.com/php-tuf/php-tuf/pull/173

**Comment by tedbow** [comment]
fixed in #173
