### ISSUE TITLE
Make sure all methods have return type where possible

### ISSUE THREAD

**Issue by tedbow** [php-tuf/php-tuf#152]
We use return types but not consistently. We should use return types whenever possible. 

This might be several PRs depending on the scope of each one. Maybe 1 for `/src` and 1 for `/tests`

**Comment by ajfwebdev** [comment]
I started working on this in [a fork](https://github.com/ajfwebdev/php-tuf). My working branch is feature/152-add-return-types

**Comment by ajfwebdev** [comment]
I submitted a PR with my changes: https://github.com/php-tuf/php-tuf/pull/167/files
The PR was reviewed and merged. Thanks, @tedbow !

**Comment by tedbow** [comment]
#167 fixed this! Thanks @ajfwebdev 

I will create a follow up issue to see if we can have phpcs rule for this. Not sure because we can't add return types if we are implementing an interface. 

We should at least be able to add a rule for the formatting if it exists
