### ISSUE TITLE
Incorrect threshold signature computation

### ISSUE THREAD

**Issue by joshuagl** [php-tuf/php-tuf#154]
The current implementation of threshold signature computation in `checkSignatures` counts each of multiple signatures with identical authorised keys separately towards the threshold. This allows an attacker with access to a single valid signing key to create multiple valid signatures in order to meet the minimum threshold of keys.

See security advisory https://github.com/theupdateframework/tuf/security/advisories/GHSA-pwqf-9h7j-7mv8 which describes a similar problem in the reference implementation.

**Comment by pwolanin** [comment]
I'll take a look at this
