### ISSUE TITLE
Document Python dependencies in DEPENDENCIES.md

### ISSUE THREAD

**Issue by webchick** [php-tuf/php-tuf#159]
Coming at you from #153!

DEPENDENCIES.md has a @todo under "Development Python dependencies"

This was added in https://github.com/php-tuf/php-tuf/commit/4f8a705431740b5c113d8ebd1dfdf6a4e18b8b91 (no associated issue that I can see)

The dependencies need documenting. :)

**Comment by phenaproxima** [comment]
As of #366, we no longer depend on Python for any reason. Closing this one out!
