### ISSUE TITLE
Research/document what confined_target_dirs is for

### ISSUE THREAD

**Issue by webchick** [php-tuf/php-tuf#161]
Greetings! Coming at you from #153!

There's a @todo in the constructor documentation of class Updater at https://github.com/php-tuf/php-tuf/blob/main/src/Client/Updater.php#L99 which states:

```
     *     - confined_target_dirs: (array) @todo What is this for?
```

I also don't know! But we should document it! ;)

**Comment by jku** [comment]
The python implementation itself is not consistent in defining what it is: https://github.com/theupdateframework/tuf/issues/1118

... but the intention is to let the client define a list of target path prefixes per mirror: that only targets under those prefixes would be considered from that mirror.

I'll mention that in python-tuf we've decided to not support mirrors in the Updater component of the "new client" that's currently in review: so the mirrors structure does not exist at all

**Comment by phenaproxima** [comment]
Not only that, but the confined_target_dirs argument is removed from `Updater::__construct()` anyway. I think we can close this.
