### ISSUE TITLE
Should we use hash_equals() to compare hashes?

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#166]
The PHP documentation describes hash_equals() thusly: "Timing attack safe string comparison".

I think that we are, in some places, using === to compare known hashes with computed hashes. I'm no security expert, so I pose this question to someone(s) who is: should we replace these with hash_equals() to guard against timing attacks?

@davidstrauss's input would be helpful here, so assigning to him, but any knowledgeable person should feel free to chime in.

**Comment by pwolanin** [comment]
I don't think there is any possibility for timing attack here - in any case the hashes are already known and public.  It matters when an attacker controls some input that's hashed and compared to a hash that's not known to the attacker.

php.net says: "for instance, when testing crypt() password hashes."

**Comment by phenaproxima** [comment]
OK, after a bit of discussion with @pwolanin in Slack, this makes sense. If timing attacks only matter when the hashes are _not_ known to the attacker, then this would be needed. But we're dealing only with public hashes, so it doesn't matter. Closing!
