### ISSUE TITLE
Validate key type of $signatureMeta in Updater::verifySingleSignature()

### ISSUE THREAD

**Issue by webchick** [php-tuf/php-tuf#168]
Coming at you from #153!

There's an outstanding @todo at https://github.com/php-tuf/php-tuf/blob/main/src/Client/Updater.php#L389 which states:

```
        // Encode the pubkey and signature, and check that the signature is
        // valid for the given data and pubkey.
        $pubkeyBytes = hex2bin($pubkey);
        $sigBytes = hex2bin($signatureMeta['sig']);
        // @todo Check that the key type in $signatureMeta is ed25519; return
        //     false if not.
        return \sodium_crypto_sign_verify_detached($sigBytes, $bytes, $pubkeyBytes);
```

Let's do it!

**Comment by xjm** [comment]
So apparently we only plan to support `ed25519`. (We discussed early on that we're fine with not supporting RSA by default.) However, this is not documented anywhere! We need to document this in the readme if we go ahead with this approach.

**Comment by phenaproxima** [comment]
This is already a thing, although done in a different place: https://github.com/php-tuf/php-tuf/blob/main/src/KeyDB.php#L91

You can't add a key that's not `ed25519`. However, this could certainly use test coverage.
