### ISSUE TITLE
Document server-side use of Python TUF

### ISSUE THREAD

**Issue by davidstrauss** [php-tuf/php-tuf#2]
Review the capabilities of Python TUF and document how we'll want to invoke it as part of operating project infrastructure.

Procedures will need to cover several things:

- [ ] Initial root key setup
- [ ] Use with YubiHSM root keys
- [ ] Rotation ceremonies
- [ ] How infrastructure should be deployed (across message queues, etc.)

Changes to the repo for this may involves various utility scripts.

**Comment by davidstrauss** [comment]
Probably useful to leverage the fixture creation scripts in #3 to create this.

**Comment by davidstrauss** [comment]
Python TUF CLI documentation: https://github.com/theupdateframework/tuf/blob/develop/docs/CLI.mda

**Comment by joshuagl** [comment]
For reference Trail of Bits developed a runbook for the PSF to use in key-generation and signing ceremonies for TUF on PyPI: https://github.com/trailofbits/psf-tuf-runbook

**Comment by phenaproxima** [comment]
This is a non-issue. PHP-TUF itself no longer uses Python, and the server side (Rugged), although built in Python, isn't our concern.
