### ISSUE TITLE
fixture-builder uses deprecated python-tuf

### ISSUE THREAD

**Issue by jku** [php-tuf/php-tuf#256]
python-tuf has recently removed the "legacy" code in git, including the repository_tool that FixtureBuilder uses.

If you're considering upgrading, I'd estimate it's not a large amount of work but the APIs are certainly completely different -- there is nothing like repository_tool in python-tuf now. 

Code that might be helpful: There is a [Repo example](https://github.com/theupdateframework/python-tuf/tree/develop/examples/repo_example) but also a [RepositorySimulator](https://github.com/theupdateframework/python-tuf/blob/develop/tests/repository_simulator.py) that might look familiar: It contains helpers to construct test repositories.

**Comment by phenaproxima** [comment]
I ended up writing a repository simulator in #366, in pure PHP. No Python.

That simulator should not be considered a replacement for the reference implementation of TUF, but it gets us as far as we need to go for testing purposes. It generates the _same exact metadata files_ as the reference implementation did, except for course for different encryption keys and expiration dates.

**Comment by phenaproxima** [comment]
#366 is merged!
