### ISSUE TITLE
Support TUF repos that do not use consistent snapshots

### ISSUE THREAD

**Issue by ergonlogic** [php-tuf/php-tuf#265]
Related to #98.

We currently enforce consistent snapshots in two ways, by:
1. validating that root metadata has consistent snapshots enabled (in [src/Metadata/RootMetadata.php](https://github.com/php-tuf/php-tuf/blob/main/src/Metadata/RootMetadata.php#L44)), and
2. throwing exceptions when consistent snapshots is not enabled (in [src/Client/Updater.php](https://github.com/php-tuf/php-tuf/blob/main/src/Client/Updater.php))

I've started on a fix in my [fork over on gitlab](https://gitlab.com/drupal-infrastructure/package-signing/php-tuf-client/-/commit/cb1056e20e8a8dcd8cabb9a96fc28c7334e65f4a).

**Comment by phenaproxima** [comment]
This was done in #278.

**Comment by ergonlogic** [comment]
In ergonlogic/php-tuf@fc2608a7, I added a change ("Make delegations optional.") that wasn't strictly related to this issue. I'll open a new issue to address that.
