### ISSUE TITLE
Generate test fixtures in PHP, and on-demand

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#288]
As I work on this library, I find that our test fixtures, and the way we use them in our PHP-based tests, are a major pain point. I think we're held back by the fact that we generate the fixtures independently of the tests themselves.

* To test different scenarios, we are normally forced to repurpose an existing "close enough" fixture, which means we often cannot test edge cases.
* The fixtures are not well-documented; normally the most you have is a brief Python comment, and a short name that doesn't explain much. (It's virtually impossible to explain the kind of complexity of the fixtures in a short name anyway, so this isn't really our fault.) You don't necessarily know what scenario a given fixture is setting up, and therefore you don't have much clarity into what a test is actually testing.
* If you want to change the fixtures, or test an edge case, you can't really do it without writing a whole new fixture in Python. Even if it's just a minor variation of an existing fixture. It is a security risk if we're not able to test edge cases easily. 
* This is a PHP library, tested in PHP, but it effectively bars people from contributing (i.e., adding test coverage) unless they are conversant in Python.

I think these are all serious maintainability problems, and I propose a new approach to solve them.

We still need Python to generate our fixtures, but I think we should abstract that stuff away from the PHP developers we expect to work on our code. Therefore, I think we should introduce a new base class for tests, `FixtureTestBase`.

During setUp(), tests written on top of this class will create a new, randomly-named temporary directory that gets automatically cleaned up during tearDown() (much the same way that Drupal's build tests do). This workspace will contain a single file of Python code. `FixtureTestBase` will contain all the same methods as the Python `FixtureBuilder` class. As these methods are called, they will generate Python code in the workspace, and then finally, when things look right, it will invoke `pipenv run python /full/path/to/temporary/script.py` and generate the complete fixture, using Python, right there in the temporary workspace. The test can then create an Updater instance which points to that temporary workspace, and go about its business from there.

In other words: let's generate fixtures on the fly, tailored to test _exactly_ what we want, rather than use pre-built "close enough" fixtures that are, at best, unclear and difficult to use. I think this will:

* Make tests much clearer, easier to write, and more maintainable.
* Let PHP developers focus on writing PHP.
* Allow us to test tricky edge cases and keep our security bases covered.
* Allow us to ensure that tests are properly setting up what they need, rather than having to approximate it.

The cons of this approach:

* This will make the tests slower. In my experimentation, generating the fixture takes about 1-3 seconds. So each test case that needs to generate a fixture -- that is, most of them -- will take 2-4 seconds to run. With hundreds of test cases already existing, I estimate that test runs will take about 7-10 minutes right now, and CI builds will obviously also take longer

One thing @tedbow brought up is that, if we do this, we will lose the safety of knowing that our fixtures didn't change in some unexpected way (i.e., by underlying changes in the Python library or its dependencies). This is something we currently check with `fixtures/**/hash.txt` -- if that file changes without corresponding changes in the relevant fixture's Python code, then we know something unexpected has happened. My opinion is that all this ever saved us from was _us_ introducing accidental fixture changes. If the Python TUF library or its dependencies change -- which is currently impossible because they are pinned -- then the fixtures could already be modified in ways we didn't explicitly cause. Because the Python TUF library is the *reference implementation* of TUF, I personally think we should trust it to do the right thing.

**Comment by wimleers** [comment]
Without knowing anything about this … can we instead _commit_ the generated fixtures and have tests _that are significantly faster than generating a fixture_ to verify the fixtures are still in sync? That way everything could be in PHP, but we wouldn't pay a 7–10 test duration penalty?

**Comment by phenaproxima** [comment]
We used to commit the complete generated fixtures, but that was removed because it made review painful. Very large PRs with inscrutable JSON changes.

The problem here is less "to use PHP or not use PHP", it's the fact that pre-generating the fixtures _at all_ is problematic. Pre-generating them means we always have to be able to identify them in a clear way, and understand exactly what they're setting up. That's what makes this so difficult.

That said, if we can find a way to generate the fixtures ahead of time in PHP, as _part of_ the relevant test coverage, I still think that would improve maintainability.

**Comment by phenaproxima** [comment]
Having said that, @wimleers, I can think of a few interesting ways to do what you're suggesting.

For example, we could put the fixture-generating code into specific public methods of a given test class, and then run only those with `phpunit --group fixtures` or similar. (The fixtures could be deterministically identified by hashing the generated Python code.) Then those generated fixtures could be reused by the actual test methods.

I think the main issue there is that it would take some hacking and careful API design, and could (should?) be done as a follow-up.

**Comment by phenaproxima** [comment]
Thinking more about that, maybe I could write `FixtureTestBase` in such a way that it uses an existing fixture _if there is one_ (determined by hashing the Python code), or creating it if not.

**Comment by davidstrauss** [comment]
I certainly have no problem in principle with generating tests on-demand. When we originally created the fixtures, I put a fair amount of work into ensuring that generation was more-or-less deterministic. I even did some work with upstream to troubleshoot aspects that weren't behaving. It should be possible to generate identical fixtures over and over.

I recall us moving to committing (really, capturing, given that a tarball archive would have accomplished the same) the fixtures to avoid requiring a Python toolchain for most development purposes. In some sense, we're choosing here between whether the Python toolchain is a hurdle for adding new fixtures versus running tests at all.

My other, longer-term goal was to get a suite of tests -- derived from our work or otherwise -- as a conformance suite usable by all TUF implementations. (It's certainly been a lot of work building out the fixtures we've needed!) This goal is made somewhat harder by wrapping fixture generation in a combination of Python and PHP, as upstream is only Python for the reference implementation.

I also can't shake the feeling here that we're doing something wrong if the approach for getting coverage involves creating a suite of fixtures for each branch of logic in code. Are there mocks or other high-level forms of inject-able context and state we could rely on more flexibly than files on disk? The fixtures were really intended to support interoperability and integration testing, not 100% code coverage.

On the other hand, I guess it's not bad to be creating such a proliferation of fixtures, a set that represents many nuanced situations a TUF library encounters.

Given all that, my inclination is to not block maintainers when they ask for things as long as relevant context is taken into account -- which I've dropped above. How we generate/store test fixtures is a decision we've changed before and one we can change again if the necessity arises. This doesn't impact actual consumers of the PHP-TUF library much.

**Comment by rdimitrov** [comment]
> My other, longer-term goal was to get a suite of tests -- derived from our work or otherwise -- as a conformance suite usable by all TUF implementations. (It's certainly been a lot of work building out the fixtures we've needed!) This goal is made somewhat harder by wrapping fixture generation in a combination of Python and PHP, as upstream is only Python for the reference implementation.

Excuse me for hopping in on this thread, but wanted to share that I'm in favor of the idea of having something like a suite of tests 👍 Not sure how difficult it would be to implement such a thing, but it was something I thought of too once I got started with TUF. There are several implementations now testing similar or even the same scenarios, so it would definitely make sense if it would be possible to have a consolidated suite that can be language/implementation agnostic.

**Comment by phenaproxima** [comment]
I have never been against that idea, but that would require round agreement on what a good, solid set of scenarios would be. As far as I know, we've never had a discussion like that.

And even then, it makes sense to try and test as many different code paths as possible. :)

**Comment by phenaproxima** [comment]
> I also can't shake the feeling here that we're doing something wrong if the approach for getting coverage involves creating a suite of fixtures for each branch of logic in code. Are there mocks or other high-level forms of inject-able context and state we could rely on more flexibly than files on disk?

I've been thinking about this. I tend to agree with you, overall.

I wonder if introducing a server-side abstraction layer would help us improve this situation. Something analogous to the client-side `StorageInterface`, but for the server. If we did that, then maybe we could have tests which return mocked metadata objects that can simulate things like rollback attacks, freeze attacks, bad signatures, etc.

**Comment by phenaproxima** [comment]
Things have changed a bit, and I don't think we really need to do this, at least not exactly as I initially described. Closing.
