### ISSUE TITLE
Use Symfony 6.1's Unique constraint

### ISSUE THREAD

**Issue by phenaproxima** [php-tuf/php-tuf#317]
In #314, we added some validation that would be a perfect fit for Symfony's `Unique` validation constraint. However, we couldn't use it because we'd need to use the constraint's `fields` option, which was only added in Symfony 6.1 (see https://symfony.com/doc/current/reference/constraints/Unique.html#fields). Adopting Symfony 6.1 would necessitate requiring PHP 8.1 at a minimum, and dropping support for Symfony 4 and 5. So, for now, we're just doing custom validation.

But, when we're ready to require PHP 8.1, maybe we can require Symfony 6.1 as well, and then refactor the validation to use the `Unique` constraint.

**Comment by tedbow** [comment]
We now require PHP 8.1 https://github.com/php-tuf/php-tuf/pull/363
