### ISSUE TITLE
Implement target validation

### ISSUE THREAD

**Issue by mbaynton** [php-tuf/php-tuf#35]
Work to date only covers refreshing the repository metadata / polling for presence of new targets to download. The other high level operation an application requests TUF libraries to do is to download (or at least verify) a "target", or essentially a file that's downloadable.

We should totally do that.

**Comment by xjm** [comment]
Here's the stub method:
```
commit 3d5991f33483c76c6050c9eebd84f7554c3c6f15
Author: xjm <xjm@65776.no-reply.drupal.org>
Date:   Tue Aug 11 06:05:55 2020 -0500

    Remove empty validateTarget() method for now, which is empty and dead code ATM. #35 will reimplement it.

diff --git b/src/Client/Updater.php a/src/Client/Updater.php
index d561913..6aa960a 100644
--- b/src/Client/Updater.php
+++ a/src/Client/Updater.php
@@ -212,6 +212,22 @@ class Updater
         }
     }
 
+  /**
+   * Validates a target.
+   *
+   * @param $targetRepoPath
+   * @param $targetStream
+   *
+   * @return bool
+   *   Returns true if the target validates.
+   *
+   * @todo implement target validation.
+   *     https://github.com/php-tuf/php-tuf/issues/35
+   */
+    public function validateTarget($targetRepoPath, $targetStream) : bool
+    {
+    }
+
     protected function checkSignatures($verifiableStructure, $type)
     {
         $signatures = $verifiableStructure['signatures'];
```

**Comment by phenaproxima** [comment]
I think we have this now, with the implementation of the `Updater::verify()` method. I'll leave this issue open for now but I suspect it's outdated and can be closed.

**Comment by phenaproxima** [comment]
This has long since been completed :) The way to do it is call `Updater::download()`, which will download the target, verify it transparently, and return it as a stream.

It's time to close this.
