### ISSUE TITLE
Example signing responsibility workflow: Drupal project 

### ISSUE THREAD

**Issue by hestenet** [php-tuf/php-tuf#4]
### How are update packages published in this project? 

In Drupal, updates.drupal.org is a central repository of packaged releases of Drupal and its contributed modules, themes, distributions, etc. updates.drupal.org serves static meta data for Composer/Packagist, as well as the tar.gz and zip files. 

### Who has access to publish these update packages?

The creation of a new tagged release on Drupal.org by a project maintainer triggers the infrastructure packaging process. 

### Is the infrastructure for serving updates centralized or decentralized? 

In Drupal, the update infrastructure is centralized on Drupal.org

### Who would perform the signing? 

Package signing is currently performed by the Drupal infrastructure signing oracle server, with the intermediate key being rotated by physical HSM key holders on the Drupal infrastructure team every 90 days. (Currently a php-signify based implementation). 

We might consider adding some sort of signing precondition on packages/releases/commits or similar. e.g: we could require a project maintainer to sign - and have the signing oracle only generate a signed package when the project maintainer had signed the release commit. 

That may be more complexity than the Drupal project needs at this time.

**Comment by xjm** [comment]
Diagram of a proposed updated infrastructure for Drupal.org with TUF:
https://docs.google.com/drawings/d/1dtcGZ6VTy8Q34pGfy72ioJpkCPfKz6yzgBPdjr3UjhA/edit?ts=5f29c2fd
![Drupal org + TUF Signing](https://user-images.githubusercontent.com/1369057/89341338-c34f8c00-d666-11ea-9ed8-d17c55e78f66.png)

**Comment by phenaproxima** [comment]
I think this is largely finalized; the Drupal Association is in the process of deploying a TUF signing workflow (powered by [Rugged](https://rugged.works)) to production.

@hestenet, can we close this?
