### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by hestenet** [php-tuf/php-tuf#6]
### PHP Support

- Composer 2 supports back to PHP 5.3
- Typo3 has some other libraries that go back to PHP 5.4

However - should we set our support based on the minimum latest supported version for Typo3, Joomla, or Drupal. 

- Typo3 version 7 - goes back to 5.5 - Typo3 version 8 goes to version 7+ 
- Joomla - minimum version 5.3.10 - recommended PHP 7+
- Drupal 7 - technically supports 5.2, but realistically doesn't support below 5.3 - Drupal 8 and above is in the PHP 7+ 

#### Current Recommendation
 - Let's target a minimum compatibity with PHP 5.3 
 - Note: the cryptographic support is available going this far back using polyfills 
 - Note: We may need test targets for two different versions of PHP to span from 5.3 up to the latest 7/8

**Comment by SniperSister** [comment]
Joomla will add signed updates to Joomla 4, which is PHP 7.2+, so 5.3 wouldn't be a constraint from our side.

**Comment by bmack** [comment]
Just for the sake of completeness: We're happy with PHP 7.2+, but having it PHP 7.0 might increase adoption for others as well.

**Comment by heddn** [comment]
Then, let's close this as resolved and set minimum PHP to 5.5.
