### ISSUE TITLE
Add getter methods for different properties under "signed" for different *MetaData classes.

### ISSUE THREAD

**Issue by tedbow** [php-tuf/php-tuf#60]
Currently in https://github.com/php-tuf/php-tuf/pull/55
There are getters on MetadataBase to get the properties like 'version' and 'expires' that are common across all metadata types. 

Each metadata type will need specific getters for properties that only are applicable for that type. Like 'roles' for RootMeta data. This will make the classes more useful. For instance we could pass a RootMeta class to RolesDB.

This will probably a PR for each *MetaData class

**Comment by phenaproxima** [comment]
Since we now require PHP 8.1, I'd suggest we use `public readonly` properties were possible. Much more convenient!

**Comment by phenaproxima** [comment]
We can close this out as of #367; everything in `signed` can be accessed as a public property, but not modified thanks to `readonly`.
